//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerMenuWPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerMenuWPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap app_icons {
            get {
                object obj = ResourceManager.GetObject("app_icons", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Menu.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Menu.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hibernate.
        /// </summary>
        public static string btnHibernate {
            get {
                return ResourceManager.GetString("btnHibernate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock.
        /// </summary>
        public static string btnLock {
            get {
                return ResourceManager.GetString("btnLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Off.
        /// </summary>
        public static string btnLogOff {
            get {
                return ResourceManager.GetString("btnLogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string btnRestart {
            get {
                return ResourceManager.GetString("btnRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Off.
        /// </summary>
        public static string btnShutDown {
            get {
                return ResourceManager.GetString("btnShutDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleep.
        /// </summary>
        public static string btnSleep {
            get {
                return ResourceManager.GetString("btnSleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation Message.
        /// </summary>
        public static string cbxConfirmMsg {
            get {
                return ResourceManager.GetString("cbxConfirmMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CM Products.
        /// </summary>
        public static string Developer {
            get {
                return ResourceManager.GetString("Developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string gpOption {
            get {
                return ResourceManager.GetString("gpOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Made by CM Products.
        /// </summary>
        public static string lblDeveloper {
            get {
                return ResourceManager.GetString("lblDeveloper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting Time (in Second):.
        /// </summary>
        public static string lblWaitTime {
            get {
                return ResourceManager.GetString("lblWaitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string muAbout {
            get {
                return ResourceManager.GetString("muAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control.
        /// </summary>
        public static string muControl {
            get {
                return ResourceManager.GetString("muControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string muExit {
            get {
                return ResourceManager.GetString("muExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string muHelp {
            get {
                return ResourceManager.GetString("muHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string muLanguage {
            get {
                return ResourceManager.GetString("muLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Menu - Users Action.
        /// </summary>
        public static string strComment {
            get {
                return ResourceManager.GetString("strComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to hibernate the computer?.
        /// </summary>
        public static string strConfirmHibernate {
            get {
                return ResourceManager.GetString("strConfirmHibernate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to lock the computer?.
        /// </summary>
        public static string strConfirmLock {
            get {
                return ResourceManager.GetString("strConfirmLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to log off from the computer?.
        /// </summary>
        public static string strConfirmLogoff {
            get {
                return ResourceManager.GetString("strConfirmLogoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to reboot the computer?.
        /// </summary>
        public static string strConfirmReboot {
            get {
                return ResourceManager.GetString("strConfirmReboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to shutdown the computer?.
        /// </summary>
        public static string strConfirmShutdown {
            get {
                return ResourceManager.GetString("strConfirmShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to sleep the computer?.
        /// </summary>
        public static string strConfirmSleep {
            get {
                return ResourceManager.GetString("strConfirmSleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string strInfoTitle {
            get {
                return ResourceManager.GetString("strInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The computer is going to be restarted. Please save and close all opening files..
        /// </summary>
        public static string strRebootComment {
            get {
                return ResourceManager.GetString("strRebootComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The computer is going to be turned off. Please save and close all opening files..
        /// </summary>
        public static string strShutdownComment {
            get {
                return ResourceManager.GetString("strShutdownComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string strWarningTitle {
            get {
                return ResourceManager.GetString("strWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show confirmation message before processing power cycle.
        /// </summary>
        public static string tsConfirmMsg {
            get {
                return ResourceManager.GetString("tsConfirmMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hibernate the computer.
        /// </summary>
        public static string tsHibernate {
            get {
                return ResourceManager.GetString("tsHibernate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock the computer.
        /// </summary>
        public static string tsLock {
            get {
                return ResourceManager.GetString("tsLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off from the computer.
        /// </summary>
        public static string tsLogoff {
            get {
                return ResourceManager.GetString("tsLogoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reboot the computer.
        /// </summary>
        public static string tsReboot {
            get {
                return ResourceManager.GetString("tsReboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power off the computer.
        /// </summary>
        public static string tsShutdown {
            get {
                return ResourceManager.GetString("tsShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleep the computer.
        /// </summary>
        public static string tsSleep {
            get {
                return ResourceManager.GetString("tsSleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only support Windows Vista or above.
        /// </summary>
        public static string tsSupportVistaAbove {
            get {
                return ResourceManager.GetString("tsSupportVistaAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set timeout before processing power cycle.
        /// </summary>
        public static string tsTimeout {
            get {
                return ResourceManager.GetString("tsTimeout", resourceCulture);
            }
        }
    }
}
